name: baseflutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  flutter_riverpod: ^2.5.1
  retrofit: ^4.4.1
  floor: ^1.5.0
  json_annotation: ^4.9.0
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true
